### ISSUE TITLE
Using Nylas Ruby v3 SDK, create a code sample to create calendar

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#16]
Using Nylas Ruby v3 SDK, create a code sample to create calendar

**Comment by sharsha315** [comment]
Hi @relaxedtomato, can I have the opportunity to work on this issue.

**Comment by relaxedtomato** [comment]
@sharsha315 assigned! Thanks for taking this one on :)

**Comment by relaxedtomato** [comment]
@sharsha315  - any updates on this ticket?

**Comment by sharsha315** [comment]
Hi Ram, I am working on this. I will be submitting PR in a day or two.
Thanks for the follow up.

**Comment by sharsha315** [comment]
Hi @relaxedtomato, I have submitted the PR, kindly review the submission and provide feedback. Thank you.

**Comment by atejada** [comment]
Closes PR #95

**Comment by sharsha315** [comment]
Hi Ram, Thanks for merging the PR and Closing the issue. I very glad to
know and this could not have happened without your support and guidance.
Thank you  for your precious support. And one more thing, since this
open-source contributions are a part of the Hactoberfest 2023, I believe it
does count as the valid PR, but in Hacktoberfest website under my profile,
it showing as excluded, stating " *Your PR/MR was submitted to a repository
that was excluded from Hacktoberfest as it does not follow the values of
the event. It will not count towards your participation*". This is my first
Hacktoberfest participation and I have made 2 PR for
nylas-hacktoberfest-2023 repository, which have been approved but it's not
showing in my Hacktoberfest profile. Kindly, please can you help me from
this situation.

Regards,
Harsha S
***@***.***

**Comment by relaxedtomato** [comment]
@sharsha315 - I’m sorry to hear about this. I reached out to Hacktoberfest Support to help advise why this is happening. We completed hacktoberfest in the past years with no issue.

We’ll keep you posted!

**Comment by relaxedtomato** [comment]
@sharsha315 - Excited to hear you enjoyed working on building code samples, your contributions are super helpful for knowledge sharing and exploring Nylas!

**Comment by relaxedtomato** [comment]
Hi @sharsha315 - the good news is that all contributions to `nylas-hacktoberfest-2023` will count towards Hackatoberfest 2023 🎉 

Our repository was blocked by mistake and it has been reverted.

**Comment by sharsha315** [comment]
Thank you so much for the great news!
