### ISSUE TITLE
Using Nylas Python v3 SDK, create a code sample to delete webhook

### ISSUE THREAD

**Issue by relaxedtomato** [nylas-samples/nylas-hacktoberfest-2023#55]
Using Nylas Python v3 SDK, create a code sample to delete webhook

**Comment by navascogt** [comment]
Hi @relaxedtomato, I want to work on this issue.  That is the last one Python related!!!

**Comment by relaxedtomato** [comment]
Awesome @navascogt - excited to see the PR!

Last one for Python 🎉

**Comment by relaxedtomato** [comment]
@navascogt - any updates on this ticket?

**Comment by navascogt** [comment]
Hi @relaxedtomato, yes, I started but get blocked on how to create the webhook in order to test it. I think I found a NodeJS example in Nylas blogs, but I am trying to do my self in Python. But, if you have a better idea how I can continue I will apreciate.

**Comment by relaxedtomato** [comment]
@navascogt let us know where you are getting blocked.

In past livestreams, we went over creating webhooks using a third-party web hook tool for receiving webhooks, that maybe where you are blocked? Have a look at these two livestreams:

- (uses v2 code): [Testing Webhooks using Pipedream](https://www.youtube.com/live/3j-SJ5awynk?si=-58FBiIe6rYCcqxL)
- (uses v2 code): [Test Webhooks in Python Locally](https://www.youtube.com/live/3tLLp8dmAKk?si=8G84OolatG2fCSGH)
- (uses v3 code): [Complete your first contribution for Hacktoberfest](https://www.youtube.com/live/wmtk-9NvdBI?si=oqDu3EvjBse-5rbP)

**Comment by navascogt** [comment]
Thanks @relaxedtomato! I will check it and plan to finish today!

**Comment by navascogt** [comment]
Hi @relaxedtomato, thanks for the livestream, those were helpfully.

I will be doing the PR with the same code that I have last week, now that I have the webhook created (nicely created in Pipedream) and think the SDK have some strange behavior, sometimes I receives timeout error (debugging I discovered how to extend it in http_client.py and change a value to more than 30 seconds) and the other situation was that always received an exception with this text 'notification_email_address' in any sdk call for creating or listing the web hooks.

Because I do not have the webhook id (for the errors above) when I tried to delete received the normal error: webhook_id.not.found : record not found.

However, I think the logic must work well if the SDK works well, or maybe I have an error that I do not see.

**Comment by relaxedtomato** [comment]
@navascogt PR is accepted, let me review your comments and take a look tomorrow before we merge the PR 👍🏽

**Comment by navascogt** [comment]
Hi @relaxedtomato, regarding the issues of the exception and timeouts, I just want to know if was there an internal problem, I will be more than happy to test it again (tested right now and had the same behavior), if I can help in any way just tell me. Thanks.

**Comment by relaxedtomato** [comment]
sounds good @navascogt - going to take a look later this week

sorry, just catching up with a few things, let me circle back to this in a few days
